# Generated by Django 5.0.1 on 2026-06-15 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("job_type", models.CharField(default="full-time", max_length=50)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                            ("pending", "Pending Moderation"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_approved"],
                        name="vacancies_v_status_fb58b6_idx",
                    ),
                    models.Index(
                        fields=["employer", "status"],
                        name="vacancies_v_employe_5de1db_idx",
                    ),
                    models.Index(fields=["city"], name="vacancies_v_city_1fd706_idx"),
                ],
            },
        ),
    ]
