# Generated by Django 5.0.1 on 2026-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userprofile",
            new_name="user_profil_role_fa03e1_idx",
            old_name="users_userp_role_c31a7e_idx",
        ),
        migrations.RenameIndex(
            model_name="userprofile",
            new_name="user_profil_is_bann_bd1d26_idx",
            old_name="users_userp_is_bann_a03671_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_uid",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
