# Generated by Django 5.2.17 on 2026-09-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_test_student_alieva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, help_text='LMS StudentID from Platonus', max_length=64, null=True, unique=True),
        ),
    ]
