# Generated by Django 5.2.17 on 2026-08-17 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_careercoachchat_mock_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_login', models.CharField(blank=True, db_index=True, max_length=150)),
                ('feature', models.CharField(db_index=True, max_length=32)),
                ('endpoint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('demo', 'Demo mode')], db_index=True, default='success', max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('ai_input', models.JSONField(blank=True, default=dict)),
                ('ai_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='ai_action_l_feature_b0954b_idx'), models.Index(fields=['user', 'created_at'], name='ai_action_l_user_id_06643d_idx')],
            },
        ),
    ]
