# Generated by Django 5.0.1 on 2026-06-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vacancy_id",
                    models.CharField(
                        help_text="Reference to vacancy in Firestore", max_length=255
                    ),
                ),
                (
                    "employer_id",
                    models.CharField(help_text="Reference to employer", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("reviewing", "Проверяется"),
                            ("interview", "Собеседование"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("withdrawn", "Отозвано"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("interview_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications_as_candidate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("reviewing", "Проверяется"),
                            ("interview", "Собеседование"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("withdrawn", "Отозвано"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="applications.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Application Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="applications.application",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_applications", models.IntegerField(default=0)),
                ("pending_count", models.IntegerField(default=0)),
                ("reviewing_count", models.IntegerField(default=0)),
                ("interview_count", models.IntegerField(default=0)),
                ("accepted_count", models.IntegerField(default=0)),
                ("rejected_count", models.IntegerField(default=0)),
                ("withdrawn_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Application Statistics",
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate", "status"], name="application_candida_a79be7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["employer_id", "status"], name="application_employe_b0a494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["vacancy_id"], name="application_vacancy_060624_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "vacancy_id")},
        ),
        migrations.AddIndex(
            model_name="applicationnotification",
            index=models.Index(
                fields=["recipient", "is_read"], name="application_recipie_05156d_idx"
            ),
        ),
    ]
