# Generated by Django 5.2.17 on 2026-08-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.BigIntegerField(db_index=True, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=64)),
                ('subject_code', models.CharField(max_length=64)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alpha_mark', models.CharField(blank=True, max_length=8)),
                ('numeral_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_mark', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('subject_name_ru', models.CharField(blank=True, max_length=255)),
                ('subject_name_kz', models.CharField(blank=True, max_length=255)),
                ('subject_name_en', models.CharField(blank=True, max_length=255)),
                ('accepted', models.IntegerField(default=0)),
                ('exam_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('retake', models.IntegerField(default=0)),
                ('course_number', models.IntegerField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(default=0)),
                ('hash', models.CharField(blank=True, max_length=128)),
                ('mark_id', models.BigIntegerField(blank=True, null=True)),
                ('is_passed', models.BooleanField(blank=True, null=True)),
                ('r1', models.CharField(blank=True, max_length=32)),
                ('r2', models.CharField(blank=True, max_length=32)),
                ('pcp', models.CharField(blank=True, max_length=32)),
                ('code_en', models.CharField(blank=True, max_length=64)),
                ('code_ru', models.CharField(blank=True, max_length=64)),
                ('ignore_marks', models.IntegerField(default=0)),
                ('query_id', models.BigIntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('rewritable_subject_name_kz', models.CharField(blank=True, max_length=255)),
                ('rewritable_subject_name_ru', models.CharField(blank=True, max_length=255)),
                ('rewritable_subject_name_en', models.CharField(blank=True, max_length=255)),
                ('is_transfer_credit', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('continuance_subject_id', models.BigIntegerField(blank=True, null=True)),
                ('subject_id', models.BigIntegerField(blank=True, null=True)),
                ('rewritable_subject_code', models.CharField(blank=True, max_length=64)),
                ('is_general_exam', models.IntegerField(default=0)),
                ('ects', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('group_type_id', models.IntegerField(blank=True, null=True)),
                ('subject_study_language', models.IntegerField(blank=True, null=True)),
                ('is_additional_subject', models.IntegerField(default=0)),
                ('is_subject_with_additional_type', models.IntegerField(default=0)),
                ('is_course_work', models.IntegerField(default=0)),
                ('traditional_mark', models.IntegerField(blank=True, null=True)),
                ('calc_as_old_mark', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('subject_type', models.IntegerField(blank=True, null=True)),
                ('tup_subject_id', models.BigIntegerField(blank=True, null=True)),
                ('old_query_id', models.BigIntegerField(blank=True, null=True)),
                ('academic_difference_course', models.IntegerField(default=0)),
                ('academic_difference_term', models.IntegerField(default=0)),
                ('not_included_scholarship', models.IntegerField(default=0)),
                ('was_retaken', models.IntegerField(default=0)),
                ('re_exam_count', models.IntegerField(default=0)),
                ('re_exam_reason_types', models.CharField(blank=True, max_length=255)),
                ('previous_type', models.IntegerField(blank=True, null=True)),
                ('general_exam_tup_subject_id', models.BigIntegerField(blank=True, null=True)),
                ('degree_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'transcript',
                'ordering': ['course_number', 'term', 'subject_code'],
                'indexes': [models.Index(fields=['student_id', 'course_number', 'term'], name='transcript_student_44865a_idx'), models.Index(fields=['subject_code'], name='transcript_subject_14b6a8_idx')],
            },
        ),
    ]
