# Generated by Django 5.2.17 on 2026-08-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('students_created', models.PositiveIntegerField(default=0)),
                ('students_updated', models.PositiveIntegerField(default=0)),
                ('students_skipped', models.PositiveIntegerField(default=0)),
                ('transcripts_created', models.PositiveIntegerField(default=0)),
                ('transcripts_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lms_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
