# Generated by Django 5.2.17 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('hour', models.PositiveSmallIntegerField(default=2)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('last_scheduled_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LMS sync schedule',
                'verbose_name_plural': 'LMS sync schedule',
                'db_table': 'lms_sync_schedule',
            },
        ),
    ]
