# Generated by Django 5.2.17 on 2026-09-08 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHhVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('salary', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_hh_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_hh_vacancies',
                'ordering': ['-is_selected', '-saved_at'],
                'unique_together': {('user', 'hh_id')},
            },
        ),
    ]
